language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
env:
  matrix:
    # test all versions against OpenSSL 0.9.8
    - OPENSSL=0.9.8
    # test all versions against OpenSSL 1.0.0
    - OPENSSL=1.0.1
matrix:
  include:
    # add a pep8 test for python 2.7
    - python: 2.7
      env: TOXENV=pep8
    # add a py3pep8 test for python 3.x
    - python: 3.4
      env: TOXENV=py3pep8
  allow_failures:
    - env: TOXENV=pep8
    - env: TOXENV=py3pep8
# install requirements
install:
  # add the lucid repo for if we need OpenSSL 0.9.8
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ lucid main"
  # make sure gnupg, pgpdump, and the requested version of OpenSSL are installed
  - sudo apt-get update
  - sudo apt-get install -y gnupg pgpdump
  - if [[ "${OPENSSL}" == "0.9.8" ]]; then sudo apt-get install -y --force-yes libssl-dev/lucid; fi
  # install coveralls
  - pip install tox python-coveralls
# set TOXENV if it isn't yet
before_script:
  - if [[ -z "$TOXENV" ]]; then export TOXENV=py${TRAVIS_PYTHON_VERSION//.}; fi
# use setup.py to invoke testing via coveralls
script:
 - tox
# and report coverage to coveralls
after_success:
  coveralls