language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
# install pgpdump - it's needed for testing
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install gnupg pgpdump -qq
# command to install dependencies
install:
 - pip install -r requirements.txt
 - pip install -r requirements-test.txt
 - pip install coveralls
 - pip install .
# use setup.py to invoke testing via coveralls
script:
  py.test -vv --cov pgpy tests/
# and report coverage to coveralls
after_success:
  coveralls