language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"
  - "pypy3"
matrix:
  include:
    # add a pep8 test
    - python: 3.4
      env: TOXENV=pep8
    # add a test of setup.py using python 3.4
    - python: 3.4
      env: TOXENV=setup
    # add a setup.py test using python 2.7
    - python: 2.7
      env: TOXENV=setup27
  allow_failures:
    - env: TOXENV=pep8
    - python: "pypy"
    - python: "pypy3"
# install requirements
install:
  # make sure gnupg, pgpdump, and the requested version of OpenSSL are installed
  - sudo apt-get update
  - sudo apt-get install -y gnupg pgpdump
  # install coveralls
  - pip install tox python-coveralls
# set TOXENV if it isn't yet
before_script:
  - if [[ -z "$TOXENV" ]]; then export TOXENV=py${TRAVIS_PYTHON_VERSION//.}; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 'pypy' ]]; then export TOXENV=pypy; fi
# use setup.py to invoke testing via coveralls
script:
 - tox
# and report coverage to coveralls, but only if this was a pytest run
after_success:
  if [[ "${TOXENV}" == "py"* ]]; then coveralls; fi
